### ISSUE TITLE
ToDo App

### ISSUE THREAD

**Issue by Krdnzbyza** [Krdnzbyza/FlutterLearnExamples#7]

**Comment by VB10** [comment]
1- bu tasarım yapılacak (calendar yerıne resim gelecek) https://www.uplabs.com/posts/to-do-list-app-for-ios

**Comment by VB10** [comment]
2- tasarım için bu site kullnıacak api end point olarak https://jsonplaceholder.typicode.com/todos

**Comment by VB10** [comment]
3- Sayfa açıldığında bir loading dönecek, servisden donen cevaba göre liste çizelecek

**Comment by VB10** [comment]
4- Sayafa hiçbir sayı elle veirlemyeecek, tasarım yaparken responsive düşünceyle yapılacak ve değerler sabit olacak misal (Padding(30) yerine fınal paddingLow = Padding(30) verilerek türelecek)

**Comment by VB10** [comment]
5- Sayfa çizimi atomic olacak (yani x,y,z alt alta değil  parçalama yöntemile dışarı çıkartılacak)

**Comment by VB10** [comment]
6- Todo Card atomic olarak yapıacalak içine todo model alacak ve isCompleted alarak eğer complete ise check olacak

**Comment by VB10** [comment]
7- Bunlar yapılarken şunlardan faydalanacak FutureBuilder or  isLoading diye bir param tutara kda yapailbirsin setState diyerek, CheckBoxListTile widigetini kullancasıkn (veya herhangi ChekcBox Widgeti)
